---
# Allows for switching between specific feature packaged versions
php_repo: ppa:ondrej/php
php_package: php7.0-fpm
php_additional: ['php7.0-cli','php7.0-common', 'php7.0-json', 'php7.0-opcache', 'php7.0-mysql', 'php7.0-phpdbg', 'php7.0-mbstring', 'php7.0-gd', 'php7.0-imap', 'php7.0-ldap','php7.0-pgsql', 'php7.0-pspell', 'php7.0-recode', 'php7.0-tidy', 'php7.0-dev', 'php7.0-intl', 'php7.0-curl', 'php7.0-zip', 'php7.0-xml', 'php-redis', 'php-xdebug', 'php7.0-mcrypt']